config/routes.rb
Rails.application.routes.draw do
  resources :produtos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: %i[ show edit update destroy ]

  # GET /produtos or /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1 or /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos or /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to produto_url(@produto), notice: "Produto was successfully created." }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1 or /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to produto_url(@produto), notice: "Produto was successfully updated." }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1 or /produtos/1.json
  def destroy
    @produto.destroy!

    respond_to do |format|
      format.html { redirect_to produtos_url, notice: "Produto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produto_params
      params.require(:produto).permit(:nome, :descricao, :preco)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Produtos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/produtos/_form.html.erb
<div class="produto-form">

  <h1><%= @produto.new_record? ? "Novo Produto" : "Editar Produto" %></h1>

  <%= form_with(model: produto) do |form| %>

    <% if produto.errors.any? %>
    <div style="color: red">
    <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>
    
    <ul>
    <% produto.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>

      </div>

    <% end %>

    <div class="form-group">
      <%= form.label :nome %>
      <%= form.text_field :nome, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :descricao %>
      <%= form.text_area :descricao, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :preco %>
      <%= form.text_field :preco, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit "Salvar", class: "btn-show" %>
    </div>

  <% end %>
  
</div>

app/views/produtos/_produto.html.erb
<div class="produto-details">
  <h2>Detalhes do Produto</h2>
  <p>
  
    <strong>Nome:</strong> 
    <%= produto.nome %><br>

    <strong>Descrição:</strong> 
    <%= produto.descricao %><br>

    <strong>Preço:</strong> 
    <%= produto.preco %><br>

  </p>
</div>

app/views/produtos/edit.html.erb
<div class="produtos">

<%= render "form", produto: @produto %>

<br>

  <%= link_to "Ver Produto", @produto, class: "btn-info" %> |
  <%= link_to "Voltar aos Produtos", produtos_path, class: "btn-info" %>

</div>

app/views/produtos/index.html.erb
<div class="produtos">
<p style="color: green"><%= notice %></p>
  
<h1>Produtos</h1>


  <div id="produtos-list">

    <% @produtos.each do |produto| %>
      <%= render produto %>
      <p>
        <%= link_to "Exibir Produto", produto, class: "btn-info" %>
      </p>
    <% end %>
    
  </div>

  <div class="add-link">
    <%= link_to "Adicionar Produto", new_produto_path, class: "btn-success" %>
  </div>

</div>

app/views/produtos/new.html.erb
<div class="new-produto">

  <%= render "form", produto: @produto %>

  <br>

  <div class="back-link">
    <%= link_to "Voltar para Produtos", produtos_path, class: "btn btn-secondary" %>
  </div>
  
</div>

app/views/produtos/show.html.erb
<h1>Catálogo de Produtos</h1>

<p style="color: green"><%= notice %></p>

<%= render @produto %>

<div class="produto-actions">

  <%= link_to "Alterar", edit_produto_path(@produto), class: "btn-show" %>
  <%= button_to "Excluir", @produto, method: :delete, class: "btn-show" %>
  <%= link_to "Voltar", produtos_path, class: "btn-show" %>

</div>